### ISSUE TITLE
Unicode Decode Error 'charmap' codec can't decode

### ISSUE THREAD

**Issue by berong91** [mirumee/google-i18n-address#22]
Getting this error when trying to install the package. 

I'm on Windows 7 X64, Python 3.5.3 64-bit. 

```
(env) E:\Dev\planet-b-saleor>py -3.5 -m pip install -U google-i18n-address
Collecting google-i18n-address
  Using cached google-i18n-address-2.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Duy\AppData\Local\Temp\pip-build-uq9wvzfd\google-i18n-address\setup.py", line 58, in <module>
        long_description=get_long_description(),
      File "C:\Users\Duy\AppData\Local\Temp\pip-build-uq9wvzfd\google-i18n-address\setup.py", line 50, in get_long_description
        readme = readme_file.read()
      File "C:\Python35\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 3819: character maps to <undefined>

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Duy\AppData\Local\Temp\pip-build-uq9wvzfd\google-i18n-address\
```

**Comment by berong91** [comment]
I closed this again, seems like the python on Windows just has so many trouble with package installing itself.

Moving to Cygwin to solve this problem.

**Comment by DDiran** [comment]
Does anyone have a fix for this on WIndows? Trying to get Saleor up and running but this is proving problematic as I can't get google-i18n-address to work

**Comment by patrys** [comment]
I'll take a look when I get a chance to use a Windows machine.

**Comment by DDiran** [comment]
Thanks for the quick reply - any ideas for a quick fix or temporary workaround in the meantime?

**Comment by patrys** [comment]
Can you test with current `master`? It seems e40a608652e85280295723d874bbefae072bf99a should fix this.

**Comment by DDiran** [comment]
Yep working fine now!
I did a `pip install git+https://github.com/mirumee/google-i18n-address/`
Thanks!!

**Comment by patrys** [comment]
I've pushed a new release that contains the fix.

**Comment by hugoalmeidad2r** [comment]
Hey guys... still have this error... 😟 Any idea how to fix it?

**Comment by DDiran** [comment]
Hey @hugoalmeidad2r did you try `pip install git+https://github.com/mirumee/google-i18n-address/`?

**Comment by hugoalmeidad2r** [comment]
I did. The problem persists still... :( any more ideas? Em 30/09/2017 9:09 a.m., DDiran <notifications@github.com> escreveu:Hey @hugoalmeidad2r did you try pip install git+https://github.com/mirumee/google-i18n-address/?
